server:
  port: 8081
spring:
  application:
    name: mod-mosaic
  threads:
    virtual:
      enabled: true
  datasource:
    username: ${DB_USERNAME:folio_admin}
    password: ${DB_PASSWORD:folio_admin}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:okapi_modules}
  liquibase:
    change-log: classpath:changelog/changelog-master.xml
  jpa:
    show-sql: false
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: non_null
  cloud:
    openfeign:
      okhttp:
        enabled: true
folio:
  environment: ${ENV:folio}
  okapi-url: ${OKAPI_URL:http://sidecar:8081}
  tenant:
    validation:
      enabled: true
management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: info,health,liquibase,threaddump,heapdump,loggers
